### ISSUE TITLE
Download link is broken

### ISSUE THREAD

**Issue by IzzySoft** [alexmercerind/audire#2]
Nothing there at [GitHub Releases](https://github.com/alexmercerind/audire/releases). Will you add the APK later? :wink:

**Comment by alexmercerind** [comment]
Hello @IzzySoft,

I think GitHub is somehow screwing it, there's a release:

- https://github.com/alexmercerind/audire/releases
- https://github.com/alexmercerind/audire/releases/tag/v1.0-1

I updated the URL in README to be:

- https://github.com/alexmercerind/audire/releases/latest

Thanks!

**Comment by IzzySoft** [comment]
Ah, I see, you've tapped into *that* Github bug – welcome to the club! Guess you've deleted and re-created the tag, pointing to the same commit again? That's one of the triggers I know. This bug becomes more widespread lately it seems, though MS/Github doesn't want to acknowledge it.

So thanks for pointing to where it is! Old trick (as old as that bug I guess): append `/latest` to the releases link in your Readme … Ah, hehe, you already did, great! That's one of the work-arounds I've learned for that :see_no_evil:

OK, checking the APK… wonderful! Fully FOSS :heart_eyes: License… Great! Metadata… Hm, no description. OK, let me write up something… Done. How do you like this:

![image](https://github.com/alexmercerind/audire/assets/6781438/a635afef-656a-4efd-ba15-3b48009955d0)

After the next sync around 5 pm UTC, that's what you will [find here](https://apt.izzysoft.de/packages/com.alexmercerind.audire/) – and you're welcome to [pick a badge](https://gitlab.com/IzzyOnDroid/repo/#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it) linking there, e.g. from your Readme. New versions are picked up automatically within 24h of your creating a new tag and adding the APK to it (well, unless Github messes up again, then you'd need to ping me for a manual update).

If you want me to, I can open a PR sending you the metadata in Fastlane structures, so you can maintain how your app is presented. And maybe even build on that – like adding a featureGraphic or even per-release changelogs. You'd be welcome using my [Fastlane Cheat Sheet](https://gitlab.com/-/snippets/1895688) for guidance with that.

Btw: You will keep the tag naming pattern (`v<versionName>-<versionCode>`) with future releases I hope?

**Comment by alexmercerind** [comment]
Hi!

Apologies for delayed affirmation. I added IzzySoft link to the README. The description seems good to me.

<hr>

I think it should be "This app uses the APIs of ~~Spotify~~ Shazam & AUDD.".

> You will keep the tag naming pattern (v<versionName>-<versionCode>) with future releases I hope?

Yeah! I think it's suitable because this project only supports Android.

Thanks!

**Comment by IzzySoft** [comment]
> I added IzzySoft link to the README. The description seems good to me.

Thanks! So do you want me to provide the resulting metadata in Fastlane format via PR, as described above?

> I think it should be "This app uses the APIs of ~~Spotify~~ Shazam & AUDD.".

Ouch, right. Fixed, thanks! And good to know the tag names will stick with the pattern. So auto-updates in my repo should work fine.
