### ISSUE TITLE
[Enhancement] QS Tile

### ISSUE THREAD

**Issue by HikaruIchijyo** [alexmercerind/audire#3]
A qs tile which when clicked starts recognizing the song immediately 
Just like shazam.
So that i can switch here

**Comment by alexmercerind** [comment]
It has been added in the latest update: [v1.1 (2)](https://github.com/alexmercerind/audire/releases/tag/v1.1-2)

Please wait for few days if you've installed the application from Google Play.

Thanks!

![](https://github.com/alexmercerind/audire/assets/28951144/9e0920e9-64bd-4c98-907a-a844dd9e6102)

**Comment by alexmercerind** [comment]
Currently it launches the application's activity in recording state... Ideally I think it would be better to recognize in background (without launching activity), in order to not stop already playing video etc. for example.

For that, #13 will be required.

Thanks!

**Comment by Turhvjbufv** [comment]
Maybe also add a little pop up on screen like Shazam can do, so you know it's working(after you finish with #13)

**Comment by HikaruIchijyo** [comment]
> Maybe also add a little pop up on screen like Shazam can do, so you know it's working(after you finish with #13)

Better
