### ISSUE TITLE
[Enhancement] Add a favorite page

### ISSUE THREAD

**Issue by N3koSempai** [alexmercerind/audire#6]
Add a favorite section and a button for save the  song details in the favorite section.

**Comment by alexmercerind** [comment]
The like functionality has been added:

<table>
<tr>
<td>
<img src="https://github.com/alexmercerind/audire/assets/28951144/b9a4c503-7e85-4969-b34e-f80c5b754ccb">
</td>
<td>
<img src="https://github.com/alexmercerind/audire/assets/28951144/52cf18d5-bd28-4c86-be0a-99f1a214e0d5">
</td>
</tr>
</table>

**Comment by alexmercerind** [comment]
Hi!

It has been added in the latest release (along with QS Tile & search):

https://github.com/alexmercerind/audire/releases/tag/v1.1-2

Please wait for few days if you've installed the application from Google Play.
